#!/bin/bash
cmake -B build -S . \
	-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/bin \
	-DEXATN_BUILD_TESTS=TRUE \
	-DBLAS_LIB=MKL -DBLAS_PATH=$MKLROOT -DPATH_INTEL_ROOT=$INTEL_HOME \
	-DMPI_LIB=OPENMPI -DMPI_ROOT_DIR=$(which mpirun)/../
